// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d1c3e9a6-a467-4e8f-9b23-3d3210e816db";
const char SSID[] = "Vodafone-A62045736";    // Network SSID (name)
const char PASS[] = "FamigliaBolelli2020@";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "b!yn0R6lP?CLNaBLPCVTTJ7kW";    // Secret device password

void onOpenGateCommandChange(){
  open_gate();
  Serial.println(F("[IOT Service] Opening gate..."));
};//command on change of open_gate_command change

bool open_gate_command;//IOT cloud bool variable

//Cloud initialization
void init_arduino_cloud(){
  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(open_gate_command, READWRITE, ON_CHANGE, onOpenGateCommandChange);
}

//conn handler initialization
WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
